#!/usr/bin/env bash
set -euo pipefail

# Offline calibration; requires rsvg-convert, ImageMagick and Node.js.
# Prints QML JavaScript to stdout. SVG files are left unchanged.
project_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)

printf '%s\n' '.pragma library' '' \
    '// Generated by scripts/qweather-icon-offsets.sh for QWeather Icons 1.8.0.' \
    '// [x, y] offsets in a 16px icon box, rounded to quarter pixels.' \
    '// Center of mass is weighted by pixel alpha; optical alignment is approximate.' \
    'var offsets = {'

for icon in "$project_dir"/assets/qweather/*-fill.svg; do
    rsvg-convert --width 256 --height 256 "$icon" |
        magick png:- -depth 8 rgba:- |
        node -e '
            const pixels = require("node:fs").readFileSync(0);
            const resolution = 256;
            if (pixels.length !== resolution * resolution * 4)
                throw new Error("Unexpected raster size");
            let mass = 0, x = 0, y = 0;
            for (let i = 0; i < pixels.length; i += 4) {
                const alpha = pixels[i + 3];
                const pixel = i / 4;
                mass += alpha;
                x += (pixel % resolution + 0.5) * alpha;
                y += (Math.floor(pixel / resolution) + 0.5) * alpha;
            }
            if (mass === 0)
                throw new Error("Empty icon");
            const offset = moment => Math.round((8 - moment / mass * 16 / resolution) * 4) / 4;
            const code = process.argv[1].replace("-fill.svg", "");
            console.log("    " + JSON.stringify(code) + ": [" + offset(x) + ", " + offset(y) + "],");
        ' "${icon##*/}"
done

printf '%s\n' '};'
