#!/usr/bin/env bash
set -euo pipefail

# Offline calibration; requires rsvg-convert, ImageMagick and Node.js.
# Prints a JavaScript module to stdout. SVG files are left unchanged.
project_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)

printf '%s\n' \
    '// Generated by scripts/qweather-icon-offsets.sh for QWeather Icons 1.8.0.' \
    '// [x, y] offsets in a 16px icon box, rounded to quarter pixels.' \
    '// Start from the visible bounds center, then move 25% toward the alpha centroid.' \
    '// This is a conservative optical-alignment heuristic, not a perceptual model.' \
    'export const offsets = {'

for icon in "$project_dir"/assets/qweather/*-fill.svg; do
    rsvg-convert --width 256 --height 256 "$icon" |
        magick png:- -depth 8 rgba:- |
        node -e '
            const pixels = require("node:fs").readFileSync(0);
            const resolution = 256;
            if (pixels.length !== resolution * resolution * 4)
                throw new Error("Unexpected raster size");
            let mass = 0, x = 0, y = 0;
            let left = resolution, right = 0, top = resolution, bottom = 0;
            for (let i = 0; i < pixels.length; i += 4) {
                const alpha = pixels[i + 3];
                const pixel = i / 4;
                const px = pixel % resolution;
                const py = Math.floor(pixel / resolution);
                mass += alpha;
                x += (px + 0.5) * alpha;
                y += (py + 0.5) * alpha;
                if (alpha >= 128) {
                    left = Math.min(left, px);
                    right = Math.max(right, px + 1);
                    top = Math.min(top, py);
                    bottom = Math.max(bottom, py + 1);
                }
            }
            if (mass === 0)
                throw new Error("Empty icon");
            const offset = (moment, start, end) => {
                const boundsCenter = (start + end) / 2;
                const alphaCenter = moment / mass;
                const center = boundsCenter + (alphaCenter - boundsCenter) * 0.25;
                return Math.round((8 - center * 16 / resolution) * 4) / 4;
            };
            const code = process.argv[1].replace("-fill.svg", "");
            console.log("    " + JSON.stringify(code) + ": [" + offset(x, left, right) + ", " + offset(y, top, bottom) + "],");
        ' "${icon##*/}"
done

printf '%s\n' '};'
